### PR TITLE
New commit

### PR DESCRIPTION
**Pull request by hobby-lc**
New commit
- firmware_symbols.h.S : rename functions, 3.15 functions offset updated
- device6_kmod.h.S : rename functions 
- tools/syscall_names.idh : add syscall name 701 to 725 (information from PS3wiki, omitted unknown names) 
- tools/find_lv1_call.idc : tools/find_stdu.idc auto fix CRLF

### CODE REVIEW

**Comment by kakaroto** [comment]
Indentation is still not fixed. You should also learn to use 'git add -p' before every commit (and never commit with -a option) to have specific commits provide specific features instead of having multiple things in the same commit (fix crlf should have been on its own).
Anyways, I'll fix it all up and merge.
Thanks.

**Comment by kakaroto** [comment]
And btw, you didn't explain why you removed the address for USBRegisterDriver in 3.15.. was it the wrong offset? Do you have the correct offset ?

**Comment by kakaroto** [comment]
Ok, I see that the syscall names 701-726 commit was unused since I had merged another commit which added all the names already and correctly indented.So I cherry-picked the function rename commits, then used git rebase to separate the CRLF fix with the renaming into two separate commits.
I've now pushed it to the upstream repo.
Thank you for the contribution! :)

**Comment by hobby-lc** [comment]
Sorry, I'm new comer for git ~~

The old USBRegisterDriver offset in 3.15 is wrong and I just find the right one today. I will update the offset again.

**Pull request closed without merging**
