### PR TITLE
PSGrooPIC PL3 Integration

### PR DESCRIPTION
**Pull request by Noltari**
To use PSGrooPIC with PL3 we need to divide the define into defines of, at maximum, 1280 entries. If we try to use larger defines PIC compiler gives us a "recusivity error", which is obviusly a bug of the PIC compiler (CCS PCHWD).

### CODE REVIEW

**Comment by kakaroto** [comment]
Oh wow, now that's an ugly hack... 
I originally didn't really like having a macro in there, but I accepted it because it could be useful in other ways. But the original solution I proposed to the PSGroove developers is what I'll suggest to you too :
copy the bin2header file into PSGrooPIC, and modify it to output the byte array with the descriptor, so no need for a macro, and no need for a hack. Just make it take .bin files from PL3 and output your port1_descriptor.h or something.
Does that sound acceptable to you ?

**Comment by J1M** [comment]
Thanks, going to try your solution.

**Comment by Noltari** [comment]
I'm going to copy bin2header into PSGrooPIC and adapt my Makefile to build PL3 with it, but I'll keep the divided define. The reason: it's the most similar option to PSGroove, and J1M told me that the define bug was introduced in 4.088+ versions of the CCS Compiler, so perhaps in the future we can use the same macro as PSGroove.

**Comment by Noltari** [comment]
PSGrooPIC now supports official PL3. However I need to learn shell script xD.

http://github.com/Noltari/PSGrooPIC/commit/8c5299613c9a08c4f59e7f312907ca2168df6561

**Comment by J1M** [comment]
Aw ... wait for it ... some! XD

Thanks Noltari, tomorrow I´ll add to PSGrooPIC blog :)

**Comment by kakaroto** [comment]
Ok cool, I'm glad we came to an understanding :) 
It's a good idea to use the macro until the compiler is fixed, this way, minimal change to remove the hack.
I'll close this issue then!
Thanks.

**Pull request closed without merging**
